version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.12.2-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/OnlineCourse.Services.Catalog/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/OnlineCourse.IdentityServer/Dockerfile
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/OnlineCourse.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/PhotoStock/OnlineCourse.Services.PhotoStock/Dockerfile
  discount.api:
    image: discount_api_image
    build:
      context: .
      dockerfile: Services/Discount/OnlineCourse.Services.Discount/Dockerfile
  payment.api:
    image: payment_api_image
    build:
      context: .
      dockerfile: Services/Payment/OnlineCourse.Services.Payment/Dockerfile
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: Services/Order/OnlineCourse.Services.Order.API/Dockerfile
  gateway.api:
    image: gateway_api_image
    build:
      context: .
      dockerfile: OnlineCourse.Gateway/Dockerfile
  aspnetcoremvc.web:
    image: aspnetcoremvc_web_image
    build:
      context: .
      dockerfile: Frontends/OnlineCourse.Web/Dockerfile
volumes:
  catalogdb_volume:
  discount_volume:
  identitydb_volume:
  orderdb_volume:
